version: "3.7"
volumes:
  minio-data:
networks:
  default:
    internal: true
  gateway:
    external:
      name: gateway
services:
  minio:
    image: minio/minio:RELEASE.2020-08-26T00-00-49Z
    # No volumes are defined here, other docker-compose.yml files such as
    # docker-compose.demo.yml are expected to extend this definition based
    # on their workflow.
    ports:
      - "9000:9000"
    networks:
      default:
      gateway: # Do not expose in production.
    volumes:
        - minio-data:/data
    command: server /data
