services:
  drupal:
    depends_on:
    - snapshot
  mariadb:
    depends_on:
    - snapshot
  matomo:
    depends_on:
    - snapshot
  minio:
    depends_on:
    - snapshot
  solr:
    depends_on:
    - snapshot
  snapshot:
    container_name: snapshot
    build: ./snapshot
    image: idc/snapshot
    volumes:
    - drupal-sites-data:/data/drupal
    - mariadb-data:/data/mariadb-data
    - mariadb-files:/data/mariadb-files
    - matomo-config-data:/data/matomo-config
    - minio-data:/data/minio
    - solr-data:/data/solr
