version: "3.7"
volumes:
  minio-data:
networks:
  default:
    internal: true
  gateway:
    external:
      name: gateway
services:
  minio:
    image: minio/minio:RELEASE.2020-08-26T00-00-49Z
    # No volumes are defined here, other docker-compose.yml files such as
    # docker-compose.demo.yml are expected to extend this definition based
    # on their workflow.
    ports:
      - "9000:9000"
    networks:
      default:
        aliases:
          - minio-${COMPOSE_PROJECT_NAME-isle-dc}.${DRUPAL_SITE_HOST-traefik.me}
      gateway: # Do not expose in production.
    volumes:
        - minio-data:/data
    command: server /data
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.idc-minio-redirectscheme.redirectscheme.permanent: "true"
      traefik.http.middlewares.idc-minio-redirectscheme.redirectscheme.scheme: https
      traefik.http.middlewares.idc-minio-stripprefix.stripprefix.prefixes: /s3
      traefik.http.middlewares.idc-minio.chain.middlewares: idc-minio-stripprefix
      traefik.http.routers.idc-minio_http.entrypoints: http
      traefik.http.routers.idc-minio_http.middlewares: idc-minio-redirectscheme
      traefik.http.routers.idc-minio_http.rule: Host(`islandora-idc.traefik.me`,`islandora-idc-traefik.me`)
        && PathPrefix(`/{path:minio|s3}`)
      traefik.http.routers.idc-minio_http.service: idc-minio
      traefik.http.routers.idc-minio_https.entrypoints: https
      traefik.http.routers.idc-minio_https.middlewares: idc-minio
      traefik.http.routers.idc-minio_https.rule: Host(`islandora-idc.traefik.me`,`islandora-idc-traefik.me`)
        && PathPrefix(`/{path:minio|s3}`)
      traefik.http.routers.idc-minio_https.tls: "true"
      traefik.http.services.idc-minio.loadbalancer.server.port: '9000'
